{
  "comments": [
    {
      "key": {
        "uuid": "74eed58f_11c29c0a",
        "filename": "services/core/java/com/android/server/am/ActivityManagerService.java",
        "patchSetId": 1
      },
      "lineNbr": 3876,
      "author": {
        "id": 1014443
      },
      "writtenOn": "2018-05-08T18:27:54Z",
      "side": 1,
      "message": "catch (InterruptedException ignored) {\n}",
      "range": {
        "startLine": 3876,
        "startChar": 25,
        "endLine": 3876,
        "endChar": 37
      },
      "revId": "2a70027e06931c59d9269cf9cd6c134343c192e6",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "2b487081_a6afb10c",
        "filename": "services/core/java/com/android/server/am/ActivityManagerService.java",
        "patchSetId": 1
      },
      "lineNbr": 3882,
      "author": {
        "id": 1014443
      },
      "writtenOn": "2018-05-08T18:27:54Z",
      "side": 1,
      "message": "not a fan of this blanket catch statement, what is it for ? The IOException from the zygote and the RemoteException from the remote service ?",
      "revId": "2a70027e06931c59d9269cf9cd6c134343c192e6",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "c40c5ee6_2ae8f1fa",
        "filename": "services/core/java/com/android/server/am/ActivityManagerService.java",
        "patchSetId": 1
      },
      "lineNbr": 3919,
      "author": {
        "id": 1014443
      },
      "writtenOn": "2018-05-08T18:27:54Z",
      "side": 1,
      "message": "revert this diff.",
      "revId": "2a70027e06931c59d9269cf9cd6c134343c192e6",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    }
  ]
}