{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "ca53885f_b92065d6",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 8
      },
      "lineNbr": 0,
      "author": {
        "id": 1352498
      },
      "writtenOn": "2021-03-16T01:13:35Z",
      "side": 1,
      "message": "looks like one testcase (which might have dependency to this one) is broken.\n\n```\njava.lang.AssertionError\njava.lang.AssertionError\n\tat org.junit.Assert.fail(Assert.java:87)\n\tat org.junit.Assert.assertTrue(Assert.java:42)\n\tat org.junit.Assert.assertFalse(Assert.java:65)\n\tat org.junit.Assert.assertFalse(Assert.java:75)\n\tat com.android.internal.telephony.dataconnection.DataConnectionTest.testOverrideUnmetered(DataConnectionTest.java:695)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)\n\tat org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)\n\tat org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:61)\n\tat org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)\n\tat org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:148)\n\tat org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:142)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.lang.Thread.run(Thread.java:920)\n```",
      "revId": "6986e790c0f15e4432c3d68a95f3012ccf117ea1",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "191a7596_0f665c67",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 8
      },
      "lineNbr": 0,
      "author": {
        "id": 1355299
      },
      "writtenOn": "2021-03-18T02:38:33Z",
      "side": 1,
      "message": "Hi, we can\u0027t view the case fail details. Is the case fail related to this change?\nWe would like to check in this change quickly to avoid more conflict. Is there anything that we need to do?\n",
      "revId": "6986e790c0f15e4432c3d68a95f3012ccf117ea1",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "772e8ffe_e67ec2ed",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 8
      },
      "lineNbr": 0,
      "author": {
        "id": 1306837
      },
      "writtenOn": "2021-03-18T02:44:34Z",
      "side": 1,
      "message": "Looked into the failure and it says:\njava.lang.AssertionError: expected: NetworkStats: elapsedRealtime\u003d0\njava.lang.AssertionError: expected: NetworkStats: elapsedRealtime\u003d0\n  [0] iface\u003dvt_data0 uid\u003d-1 set\u003dFOREGROUND tag\u003d0x0 metered\u003dYES roaming\u003dNO defaultNetwork\u003dYES rxBytes\u003d25 rxPackets\u003d0 txBytes\u003d25 txPackets\u003d0 operations\u003d0\n but was: NetworkStats: elapsedRealtime\u003d2458391\n  [0] iface\u003dvt_data00 uid\u003d-1 set\u003dFOREGROUND tag\u003d0x0 metered\u003dYES roaming\u003dNO defaultNetwork\u003dYES rxBytes\u003d25 rxPackets\u003d0 txBytes\u003d25 txPackets\u003d0 operations\u003d0\n\n\tat org.junit.Assert.fail(Assert.java:89)\n\tat kotlin.test.junit.JUnitAsserter.fail(JUnitSupport.kt:56)\n\tat kotlin.test.Asserter$DefaultImpls.assertTrue(Assertions.kt:226)\n\tat kotlin.test.junit.JUnitAsserter.assertTrue(JUnitSupport.kt:30)\n\tat kotlin.test.Asserter$DefaultImpls.assertTrue(Assertions.kt:236)\n\tat kotlin.test.junit.JUnitAsserter.assertTrue(JUnitSupport.kt:30)\n\tat kotlin.test.AssertionsKt__AssertionsKt.assertTrue(Assertions.kt:40)\n\tat kotlin.test.AssertionsKt.assertTrue(Unknown Source:1)\n\tat com.android.testutils.NetworkStatsUtilsKt.assertNetworkStatsEquals(NetworkStatsUtils.kt:68)\n\tat com.android.testutils.NetworkStatsUtilsKt.assertNetworkStatsEquals$default(NetworkStatsUtils.kt:63)\n\tat com.android.testutils.NetworkStatsUtilsKt.assertNetworkStatsEquals(Unknown Source:13)\n\tat com.android.internal.telephony.imsphone.ImsPhoneCallTrackerTest.assertVtDataUsageUpdated(ImsPhoneCallTrackerTest.java:1383)\n\tat com.android.internal.telephony.imsphone.ImsPhoneCallTrackerTest.testVtDataUsageProvider(ImsPhoneCallTrackerTest.java:1156)",
      "parentUuid": "191a7596_0f665c67",
      "revId": "6986e790c0f15e4432c3d68a95f3012ccf117ea1",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "e8e58000_73b5bdad",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 8
      },
      "lineNbr": 0,
      "author": {
        "id": 1352498
      },
      "writtenOn": "2021-03-18T02:46:08Z",
      "side": 1,
      "message": "java.lang.AssertionError: expected: NetworkStats: elapsedRealtime\u003d0\njava.lang.AssertionError: expected: NetworkStats: elapsedRealtime\u003d0\n  [0] iface\u003dvt_data0 uid\u003d-1 set\u003dFOREGROUND tag\u003d0x0 metered\u003dYES roaming\u003dNO defaultNetwork\u003dYES rxBytes\u003d25 rxPackets\u003d0 txBytes\u003d25 txPackets\u003d0 operations\u003d0\n but was: NetworkStats: elapsedRealtime\u003d2458391\n  [0] iface\u003dvt_data00 uid\u003d-1 set\u003dFOREGROUND tag\u003d0x0 metered\u003dYES roaming\u003dNO defaultNetwork\u003dYES rxBytes\u003d25 rxPackets\u003d0 txBytes\u003d25 txPackets\u003d0 operations\u003d0\n\n\tat org.junit.Assert.fail(Assert.java:89)\n\tat kotlin.test.junit.JUnitAsserter.fail(JUnitSupport.kt:56)\n\tat kotlin.test.Asserter$DefaultImpls.assertTrue(Assertions.kt:226)\n\tat kotlin.test.junit.JUnitAsserter.assertTrue(JUnitSupport.kt:30)\n\tat kotlin.test.Asserter$DefaultImpls.assertTrue(Assertions.kt:236)\n\tat kotlin.test.junit.JUnitAsserter.assertTrue(JUnitSupport.kt:30)\n\tat kotlin.test.AssertionsKt__AssertionsKt.assertTrue(Assertions.kt:40)\n\tat kotlin.test.AssertionsKt.assertTrue(Unknown Source:1)\n\tat com.android.testutils.NetworkStatsUtilsKt.assertNetworkStatsEquals(NetworkStatsUtils.kt:68)\n\tat com.android.testutils.NetworkStatsUtilsKt.assertNetworkStatsEquals$default(NetworkStatsUtils.kt:63)\n\tat com.android.testutils.NetworkStatsUtilsKt.assertNetworkStatsEquals(Unknown Source:13)\n\tat com.android.internal.telephony.imsphone.ImsPhoneCallTrackerTest.assertVtDataUsageUpdated(ImsPhoneCallTrackerTest.java:1383)\n\tat com.android.internal.telephony.imsphone.ImsPhoneCallTrackerTest.testVtDataUsageProvider(ImsPhoneCallTrackerTest.java:1156)",
      "revId": "6986e790c0f15e4432c3d68a95f3012ccf117ea1",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}